config/routes.rb
Rails.application.routes.draw do
  root to: "movies#index"

  get "movies", to: "movies#show_all_movies"
  get "directors", to: "movies#show_all_directors"
  get "longest", to: "movies#show_longest"
  get "first_last", to: "movies#show_first_last"
  get "median", to: "movies#show_median"
  get "most_wows", to: "movies#show_most_wows"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  before_action :set_class
  include HTTParty
  include MoviesHelper

  def index
  end

  def show_all_movies
    response = HTTParty.get("https://owen-wilson-wow-api.onrender.com/wows/movies")
    if response.success?
      data = response.parsed_response
      if params[:sort] == "T"
        @data = data.sort
      else
        @data = data
      end
    else
      @data = { error: "No se pudo obtener la información de la API" }
    end
  end

  def show_all_directors
    response = HTTParty.get("https://owen-wilson-wow-api.onrender.com/wows/directors")
    if response.success?
      data = response.parsed_response
      if params[:sort] == "T"
        @data = data.sort
      else
        @data = data
      end
    else
      @data = { error: "No se pudo obtener la información de la API" }
    end
  end

  def show_longest
    longest = 0
    wow_number = 0
    movie_name = ""
    director_name = ""
    poster = ""
    response = HTTParty.get("https://owen-wilson-wow-api.onrender.com/wows/movies")
    if response.success?
      @data = response.parsed_response
      @data.each do |movie|
        encoded_movie = URI.encode_www_form_component(movie)
        movie_response = HTTParty.get("https://owen-wilson-wow-api.onrender.com/wows/random?movie=#{encoded_movie}")
        if movie_response.success?
          movie_data = movie_response.parsed_response
          movie_time = movie_data[0]["movie_duration"]
          tiempo = movie_duration(movie_time)
          if tiempo > longest
            longest = tiempo
            wow_number = movie_data[0]["total_wows_in_movie"]
            movie_name = movie
            director_name = movie_data[0]["director"]
            poster = movie_data[0]["poster"]
          end
        else
          @data = { error: "No se pudo obtener la información de la API" }
        end
      end
      @time = time_formatter(longest)
      @wows = wow_number
      @movie = movie_name
      @director = director_name
      @image = poster
    else
      @data = { error: "No se pudo obtener la información de la API" }
    end
  end

  def show_first_last
    response = HTTParty.get("https://owen-wilson-wow-api.onrender.com/wows/ordered/0-9999")
    if response.success?
      @data = response.parsed_response
      @wows = [@data.first, @data.last]
      @last = @data.length
    else
      @data = { error: "No se pudo obtener la información de la API" }
    end
  end

  def show_median
    response = HTTParty.get("https://owen-wilson-wow-api.onrender.com/wows/ordered/0-9999")
    if response.success?
      @data = response.parsed_response
      len = @data.length
      if len % 2 == 0
        @wows = [[@data[(len / 2) - 1], len / 2], [@data[len / 2], (len / 2) + 1]]
      else
        @wows = [[@data[len / 2], (len + 1) / 2]]
      end
    else
      @data = { error: "No se pudo obtener la información de la API" }
    end
  end

  def show_most_wows
    response = HTTParty.get("https://owen-wilson-wow-api.onrender.com/wows/ordered/0-9999")
    if response.success?
      @data = response.parsed_response
      most_wows = 0
      @data.each do |wow|
        if wow["total_wows_in_movie"] > most_wows
          most_wows = wow["total_wows_in_movie"]
        end
      end
      movies = []
      @data.each do |wow|
        if wow["total_wows_in_movie"] == most_wows
          movies << wow unless wow["current_wow_in_movie"] > 1
        end
      end
      @wows = most_wows
      @movies = movies
    else
      @data = { error: "No se pudo obtener la información de la API" }
    end
  end

  def set_class
    @class = "rounded-md m-5 bg-orange-400/80 px-5 py-2 text-semibold border-black border-2 text-lg hover:opacity-50"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  def movie_duration(duration_string)
    horas, minutos, segundos = duration_string.split(':')
    horas = horas.to_i
    minutos = minutos.to_i
    segundos = segundos.to_i
    tiempo = segundos + (minutos * 60) + (horas * 3600)
    tiempo
  end

  def time_formatter(segundos)
    horas = segundos / 3600
    minutos = (segundos % 3600) / 60
    segundos = segundos % 60

    "#{horas} horas, #{minutos} minutos, #{segundos} segundos"
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DonandoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-Owen bg-center bg-cover h-screen">
    <main class="my-10 mx-20 flex p-10 bg-white border-black border-2 rounded">
      <%= yield %>
    </main>
  </body>
</html>

app/views/movies/index.html.erb
<div class="flex flex-col w-full">
  <div class="flex justify-center">
    <p class="text-4xl font-semibold mb-10">Owen Wilson: WOW</p>
  </div>
  <div class="flex justify-between w-full items-start">
    <%= button_to 'Películas', movies_path, method: :get, class: "rounded-md m-5 bg-orange-400/80 px-5 py-2 text-semibold border-black border-2 text-lg hover:opacity-50"%>
    <%= button_to 'Directores', directors_path, method: :get, class: @class%>
    <%= button_to 'Película Mayor Duración', longest_path, method: :get, class: @class%>
    <%= button_to 'Primero y Último', first_last_path, method: :get, class: @class%>
    <%= button_to 'Mediana', median_path, method: :get, class: @class%>
    <%= button_to 'Más WOWS', most_wows_path, method: :get, class: @class%>
  </div>
</div>

app/views/movies/show_all_directors.html.erb
<div class="flex flex-col w-full">
  <div class="flex justify-center">
    <p class="text-4xl font-semibold mb-10">Todos los Directores</p>
  </div>
  <div class="flex justify-between w-full items-start">
    <%= button_to 'Películas', movies_path, method: :get, class: @class%>
    <%= button_to 'Directores', directors_path, method: :get, class: @class%>
    <%= button_to 'Película Mayor Duración', longest_path, method: :get, class: @class%>
    <%= button_to 'Primero y Último', first_last_path, method: :get, class: @class%>
    <%= button_to 'Mediana', median_path, method: :get, class: @class%>
    <%= button_to 'Más WOWS', most_wows_path, method: :get, class: @class%>
  </div>
  <div class="flex justify-center w-full mt-10">
    <%= button_to 'Ordenar Alfabéticamente', directors_path, params: {sort: 'T'}, method: :get, class: "rounded-md m-5 bg-lime-500/80 px-5 py-2 text-semibold border-black border-2 text-lg hover:opacity-50"%>
  </div>
  <div class="flex justify-center w-full mt-5">
    <table class="w-1/2 border-2 border-black">
      <thead>
        <tr class="bg-slate-300">
          <th class="text-2xl py-2">Directores</th>
        </tr>
      </thead>
      <tbody>
        <% contador = 0 %>
        <% @data.each do |director| %>
          <% if contador % 2 == 0 %>
            <tr class="flex justify-center bg-slate-100 hover:bg-zinc-300">
              <td class="text-lg py-1"><%= director %></td>
            </tr>
          <% else %>
            <tr class="flex justify-center bg-slate-200 hover:bg-zinc-300">
              <td class="text-lg py-1"><%= director %></td>
            </tr>
          <% end %>
          <% contador += 1 %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/movies/show_all_movies.html.erb
<div class="flex flex-col w-full">
  <div class="flex justify-center">
    <p class="text-4xl font-semibold mb-10">Todas las Películas</p>
  </div>
  <div class="flex justify-between w-full items-start">
    <%= button_to 'Películas', movies_path, method: :get, class: @class%>
    <%= button_to 'Directores', directors_path, method: :get, class: @class%>
    <%= button_to 'Película Mayor Duración', longest_path, method: :get, class: @class%>
    <%= button_to 'Primero y Último', first_last_path, method: :get, class: @class%>
    <%= button_to 'Mediana', median_path, method: :get, class: @class%>
    <%= button_to 'Más WOWS', most_wows_path, method: :get, class: @class%>
  </div>
  <div class="flex justify-center w-full mt-10">
    <%= button_to 'Ordenar Alfabéticamente', movies_path, params: {sort: 'T'}, method: :get, class: "rounded-md m-5 bg-lime-500/80 px-5 py-2 text-semibold border-black border-2 text-lg hover:opacity-50"%>
  </div>
  <div class="flex justify-center w-full mt-5">
    <table class="w-1/2 border-2 border-black">
      <thead>
        <tr class="bg-slate-300">
          <th class="text-2xl py-2">Películas</th>
        </tr>
      </thead>
      <tbody>
        <% contador = 0 %>
        <% @data.each do |pelicula| %>
          <% if contador % 2 == 0 %>
            <tr class="flex justify-center bg-slate-100 hover:bg-zinc-300">
              <td class="text-lg py-1"><%= pelicula %></td>
            </tr>
          <% else %>
            <tr class="flex justify-center bg-slate-200 hover:bg-zinc-300">
              <td class="text-lg py-1"><%= pelicula %></td>
            </tr>
          <% end %>
          <% contador += 1 %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/movies/show_first_last.html.erb
<div class="flex flex-col w-full">
  <div class="flex justify-center">
    <p class="text-4xl font-semibold mb-10">Primer y Último WOW</p>
  </div>
  <div class="flex justify-between w-full items-start">
    <%= button_to 'Películas', movies_path, method: :get, class: @class%>
    <%= button_to 'Directores', directors_path, method: :get, class: @class%>
    <%= button_to 'Película Mayor Duración', longest_path, method: :get, class: @class%>
    <%= button_to 'Primero y Último', first_last_path, method: :get, class: @class%>
    <%= button_to 'Mediana', median_path, method: :get, class: @class%>
    <%= button_to 'Más WOWS', most_wows_path, method: :get, class: @class%>
  </div>
  <div class="flex justify-center w-full mt-10">
    <table class="w-11/12 border-2 border-black">
      <thead>
        <tr class="bg-slate-300">
          <th class="text-2xl py-2">Nº WOW Global</th>
          <th class="text-2xl py-2">Película</th>
          <th class="text-2xl py-2">Año</th>
          <th class="text-2xl py-2">Linea</th>
          <th class="text-2xl py-2">Nº WOWs en Película</th>
          <th class="text-2xl py-2">Imagen</th>
        </tr>
      </thead>
      <tbody>
        <% contador = 0 %>
        <% @wows.each do |wow| %>
          <% if contador % 2 == 0 %>
            <tr class="text-center text-lg my-4 bg-slate-100 hover:bg-zinc-300">
              <td>1</td>
              <td><%= wow["movie"] %></td>
              <td><%= wow["year"] %></td>
              <td class="max-w-80"><%= wow["full_line"] %></td>
              <td><%= wow["total_wows_in_movie"] %></td>
              <td class="flex justify-center items-center"><%= image_tag wow["poster"], alt: "Poster", class: "w-20 h-auto"%></td>
            </tr>
          <% else %>
            <tr class="text-center text-lg my-4 bg-slate-200 hover:bg-zinc-300">
              <td><%= @last %></td>
              <td><%= wow["movie"] %></td>
              <td><%= wow["year"] %></td>
              <td class="max-w-80"><%= wow["full_line"] %></td>
              <td><%= wow["total_wows_in_movie"] %></td>
              <td class="flex justify-center items-center"><%= image_tag wow["poster"], alt: "Poster", class: "w-20 h-auto"%></td>
            </tr>
          <% end %>
          <% contador += 1 %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/movies/show_longest.html.erb
<div class="flex flex-col w-full">
  <div class="flex justify-center">
    <p class="text-4xl font-semibold mb-10">Película más Larga</p>
  </div>
  <div class="flex justify-between w-full items-start">
    <%= button_to 'Películas', movies_path, method: :get, class: @class%>
    <%= button_to 'Directores', directors_path, method: :get, class: @class%>
    <%= button_to 'Película Mayor Duración', longest_path, method: :get, class: @class%>
    <%= button_to 'Primero y Último', first_last_path, method: :get, class: @class%>
    <%= button_to 'Mediana', median_path, method: :get, class: @class%>
    <%= button_to 'Más WOWS', most_wows_path, method: :get, class: @class%>
  </div>
  <div class="flex justify-center w-full mt-10">
    <table class="w-3/5 border-2 border-black">
      <thead>
        <tr class="bg-slate-300">
          <th class="text-2xl py-2">Película</th>
          <th class="text-2xl py-2">Duración</th>
          <th class="text-2xl py-2">Director</th>
          <th class="text-2xl py-2">WOWs</th>
        </tr>
      </thead>
      <tbody>
        <tr class="bg-slate-100 hover:bg-zinc-300 text-center py-1 text-lg">
          <td><%= @movie%></td>
          <td><%= @time%></td>
          <td><%= @director%></td>
          <td><%= @wows%></td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="flex w-full justify-center">
    <%= image_tag @image, alt: "Poster", class: "w-1/4 h-auto"%>
  </div>
</div>

app/views/movies/show_median.html.erb
<div class="flex flex-col w-full">
  <div class="flex justify-center">
    <p class="text-4xl font-semibold mb-10">El WOW Mediana</p>
  </div>
  <div class="flex justify-between w-full items-start">
    <%= button_to 'Películas', movies_path, method: :get, class: @class%>
    <%= button_to 'Directores', directors_path, method: :get, class: @class%>
    <%= button_to 'Película Mayor Duración', longest_path, method: :get, class: @class%>
    <%= button_to 'Primero y Último', first_last_path, method: :get, class: @class%>
    <%= button_to 'Mediana', median_path, method: :get, class: @class%>
  </div>
</div>

app/views/movies/show_most_wows.html.erb
<div class="flex flex-col w-full">
  <div class="flex justify-center">
    <p class="text-4xl font-semibold mb-10">Películas con Mayor cantidad de WOWs: <%= @wows %></p>
  </div>
  <div class="flex justify-between w-full items-start">
    <%= button_to 'Películas', movies_path, method: :get, class: @class%>
    <%= button_to 'Directores', directors_path, method: :get, class: @class%>
    <%= button_to 'Película Mayor Duración', longest_path, method: :get, class: @class%>
    <%= button_to 'Primero y Último', first_last_path, method: :get, class: @class%>
    <%= button_to 'Mediana', median_path, method: :get, class: @class%>
    <%= button_to 'Más WOWS', most_wows_path, method: :get, class: @class%>
  </div>
  <div class="flex justify-center w-full mt-10">
    <table class="w-3/4 border-2 border-black">
      <thead>
        <tr class="bg-slate-300">
          <th class="text-2xl py-2">Película</th>
          <th class="text-2xl py-2">Año</th>
          <th class="text-2xl py-2">Nº WOWs</th>
          <th class="text-2xl py-2">Personaje Interpretado</th>
          <th class="text-2xl py-2">Imagen</th>
        </tr>
      </thead>
      <tbody>
        <% contador = 0 %>
        <% @movies.each do |pelicula| %>
          <% if contador % 2 == 0 %>
            <tr class="text-center text-lg my-4 bg-slate-100 hover:bg-zinc-300">
              <td><%= pelicula["movie"] %></td>
              <td><%= pelicula["year"] %></td>
              <td><%= pelicula["total_wows_in_movie"] %></td>
              <td><%= pelicula["character"] %></td>
              <td class="flex justify-center items-center"><%= image_tag pelicula["poster"], alt: "Poster", class: "w-20 h-auto"%></td>
            </tr>
          <% else %>
            <tr class="text-center text-lg my-4 bg-slate-100 hover:bg-zinc-300">
              <td><%= pelicula["movie"] %></td>
              <td><%= pelicula["year"] %></td>
              <td><%= pelicula["total_wows_in_movie"] %></td>
              <td><%= pelicula["character"] %></td>
              <td class="flex justify-center items-center"><%= image_tag pelicula["poster"], alt: "Poster", class: "w-20 h-auto"%></td>
            </tr>
          <% end %>
          <% contador += 1 %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>